export default {

  FONTS: {
    primary: "'Poppins', sans-serif",
    secondary: "'Roboto', sans-serif",
    tertiary: "'DM Sans', sans-serif",

    Poppins100Medium: {
      fontFamily: 'var(--ff-primary)',
      letterSpacing: '0%',
      fontWeight: 500,
      textDecoration: 'none',
      fontSize: '1.4rem',
      marginBottom: '0px',
      lineHeight: '2.4rem',
      textTransform: 'none',
    },

    Poppins200Medium: {
      fontFamily: 'var(--ff-primary)',
      letterSpacing: '0%',
      fontWeight: 500,
      textDecoration: 'none',
      fontSize: '2rem',
      marginBottom: '0px',
      lineHeight: '160%',
      textTransform: 'none',
    },
    
    Poppins300Bold: {
      fontFamily: 'var(--ff-primary)',
      letterSpacing: '0%',
      fontWeight: 700,
      textDecoration: 'none',
      fontSize: '2.4rem',
      marginBottom: '0rem',
      lineHeight: '140%',
      textTransform: 'none',
    },
    
    Poppins300Regular: {
      fontFamily: 'var(--ff-primary)',
      letterSpacing: '0%',
      fontWeight: 400,
      textDecoration: 'none',
      fontSize: '2.4rem',
      marginBottom: '0rem',
      lineHeight: '140%',
      textTransform: 'none',
    },
    
    Poppins400Medium: {
      fontFamily: 'var(--ff-primary)',
      letterSpacing: '0%',
      fontWeight: 500, 
      textDecoration: 'none',
      fontSize: '3.2rem',
      marginBottom: '0rem',
      lineHeight: '140%',
      textTransform: 'none',
    },
    
    Poppins500Medium: {
      fontFamily: 'var(--ff-primary)',
      letterSpacing: '0%',
      fontWeight: 500, 
      textDecoration: 'none', 
      fontSize: '4rem',
      marginBottom: '0rem', 
      lineHeight: '140%',
      textTransform: 'none',
    },
    
    RobotoSmallestRegular: {
      fontFamily: 'var(--ff-secondary)',
      letterSpacing: '0%',
      fontWeight: 400, 
      textDecoration: 'none',
      fontSize: '1.2rem',
      marginBottom: '0rem', 
      lineHeight: '160%',
      textTransform: 'none',
    },
    
    RobotoSmallerRegular: {
      fontFamily: 'var(--ff-secondary)',
      letterSpacing: '0%',
      fontWeight: 400, 
      textDecoration: 'none',
      fontSize: '1.4rem',
      marginBottom: '0rem', 
      lineHeight: '160%',
      textTransform: 'none',
    },
    
    RobotoSmallerBold: {
      fontFamily: 'var(--ff-secondary)',
      letterSpacing: '0%',
      fontWeight: 700, 
      textDecoration: 'none', 
      fontSize: '1.4rem',
      marginBottom: '0rem', 
      lineHeight: '160%',
      textTransform: 'none',
    },
    
    RobotoSmallSpaced: {
      fontFamily: 'var(--ff-secondary)',
      letterSpacing: '0%',
      fontWeight: 400, 
      textDecoration: 'none',
      fontSize: '1.6rem',
      marginBottom: '0rem', 
      lineHeight: '160%',
      textTransform: 'none',
    },
    
    RobotoSmallRegular: {
      fontFamily: 'var(--ff-secondary)',
      letterSpacing: '0%',
      fontWeight: 400, 
      textDecoration: 'none',
      fontSize: '1.6rem',
      marginBottom: '0rem', 
      lineHeight: '100%',
      textTransform: 'none',
    },
    
    RobotoBigBold: {
      fontFamily: 'var(--ff-secondary)',
      letterSpacing: '0%',
      fontWeight: 700,  
      textDecoration: 'none', 
      fontSize: '2rem',
      marginBottom: '0rem', 
      lineHeight: '160%',
      textTransform: 'none',
    },
    
    RobotoBiggerBold: {
      fontFamily: 'var(--ff-secondary)',
      letterSpacing: '0%',
      fontWeight: 700, 
      textDecoration: 'none', 
      fontSize: '2.4rem',
      marginBottom: '0rem',
      lineHeight: 'Automatic',
      textTransform: 'none',
    },
    
    RobotoBiggestRegular: {
      fontFamily: 'var(--ff-secondary)',
      letterSpacing: '0%',
      fontWeight: 400, 
      textDecoration: 'none',
      fontSize: '3.2rem',
      marginBottom: '0rem',
      lineHeight: '160%',
      textTransform: 'none',
    },
    
    RobotoGiantBold: {
      fontFamily: 'var(--ff-secondary)',
      letterSpacing: '0%',
      fontWeight: 700, 
      textDecoration: 'none', 
      fontSize: '4.2rem',
      marginBottom: '0rem', 
      lineHeight: 'Automatic',
      textTransform: 'none',
    }
  },

  COLORS: {
  BACKGROUND_100: "#000405",
  BACKGROUND_200: "#00070A",
  BACKGROUND_300: "#000204",
  BACKGROUND_400: "#000A0F",
  BACKGROUND_500: "#000C12",
  BACKGROUND_600: "#00111A",
  BACKGROUND_700: "#001119",
  BACKGROUND_800: "#0D161B",
  BACKGROUND_900: "#0D1D25",
  BACKGROUND_1000: "#192227",

  GRAY_100: "#FFFFFF",
  GRAY_200: "#FFFAF1",
  GRAY_300: "#E1E1E6",
  GRAY_400: "#C4C4CC",	
  GRAY_500: "#7C7C8A",
  GRAY_600: "#76797B",
  GRAY_700: "#4D585E",
  
  GRADIENTS_100: "#000A0F",
  GRADIENTS_200: "#091E26",

  TOMATO_100: "#750310",
  TOMATO_200: "#92000E",
  TOMATO_300: "#AB222E",
  TOMATO_400: "#AB4D55",	
  CARROT_100: "#FBA94C",
  MINT_100: "#04D361",
  CAKE_200: "#82F3FF",
  CAKE_100: "#065E7C",
  },
}